### ISSUE TITLE
Plugin add not working for me

### ISSUE THREAD

**Issue by 5pitty1** [VitaliiBlagodir/cordova-plugin-datepicker#110]
Sorry, but I'm really new to cordova and when I try to add it in, i get this error:

cordova plugin add cordova-plugin-datepicker
Fetching plugin "cordova-plugin-datepicker" via plugin registry
npm http GET http://registry.cordova.io/cordova-plugin-datepicker
npm http 404 http://registry.cordova.io/cordova-plugin-datepicker
Error: 404 Not Found: cordova-plugin-datepicker
    at RegClient.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:268:14)
    at Request.self.callback (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:148:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:876:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/node_modules/npm/node_modules/request/index.js:827:12)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

**Comment by pudupa** [comment]
I'm having the same issue, not being able to add the plugin. Anyone, any help ??

>> cordova plugin add cordova-plugin-datepicker

Fetching plugin "cordova-plugin-datepicker" via npm
Failed to fetch plugin cordova-plugin-datepicker via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: connect ETIMEDOUT 23.235.40.162:443

**Comment by tripathi-swapnil** [comment]
Facing same issue

**Comment by dianaVidalC** [comment]
me too
