### ISSUE TITLE
Min and Date error in Android

### ISSUE THREAD

**Issue by Jamesmallon1** [VitaliiBlagodir/cordova-plugin-datepicker#231]
I input the UTC time in milliseconds and the plugin returns this error:
`05-09 21:11:18.708  9903 10057 D DatePickerPlugin: DatePicker called with options: [{"mode":"date","date":1494533478721,"minDate":1494447078721,"maxDate":0,"titleText":"","cancelText":"","okText":"","todayText":"","nowText":"","is24Hour":false,"androidTheme":1}]
05-09 21:11:18.708  9903 10057 E PluginManager: Uncaught exception from plugin
05-09 21:11:18.708  9903 10057 E PluginManager: java.lang.NumberFormatException: Invalid int: "1494533478721"
05-09 21:11:18.708  9903 10057 E PluginManager:         at java.lang.Integer.invalidInt(Integer.java:138)
05-09 21:11:18.708  9903 10057 E PluginManager:         at java.lang.Integer.parse(Integer.java:413)
05-09 21:11:18.708  9903 10057 E PluginManager:         at java.lang.Integer.parseInt(Integer.java:367)
05-09 21:11:18.708  9903 10057 E PluginManager:         at java.lang.Integer.parseInt(Integer.java:334)
05-09 21:11:18.708  9903 10057 E PluginManager:         at com.plugin.datepicker.DatePickerPlugin$JsonDate.fromJson(DatePickerPlugin.java:387)
05-09 21:11:18.708  9903 10057 E PluginManager:         at com.plugin.datepicker.DatePickerPlugin.show(DatePickerPlugin.java:70)
05-09 21:11:18.708  9903 10057 E PluginManager:         at com.plugin.datepicker.DatePickerPlugin.execute(DatePickerPlugin.java:60)
05-09 21:11:18.708  9903 10057 E PluginManager:         at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:98)
05-09 21:11:18.708  9903 10057 E PluginManager:         at org.apache.cordova.PluginManager.exec(PluginManager.java:132)
05-09 21:11:18.708  9903 10057 E PluginManager:         at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:57)
05-09 21:11:18.708  9903 10057 E PluginManager:         at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
05-09 21:11:18.708  9903 10057 E PluginManager:         at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
05-09 21:11:18.708  9903 10057 E PluginManager:         at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:41)
05-09 21:11:18.708  9903 10057 E PluginManager:         at android.os.Handler.dispatchMessage(Handler.java:102)
05-09 21:11:18.708  9903 10057 E PluginManager:         at android.os.Looper.loop(Looper.java:168)
05-09 21:11:18.708  9903 10057 E PluginManager:         at android.os.HandlerThread.run(HandlerThread.java:61)`

Any help?

**Comment by Jamesmallon1** [comment]
I use .valueOf() on my dates but get this error

**Comment by Jamesmallon1** [comment]
Fixed the error. 

the date field must be a regular js date object.

Strange as minDate is UTC!
