### ISSUE TITLE
First time I use it it works fine, the second time I get an error

### ISSUE THREAD

**Issue by SubjectiveEffect** [VitaliiBlagodir/cordova-plugin-datepicker#62]
My html has an ng-click="datePopup()"

The function is 

    var options = {
    date: new Date(),
    mode: 'date', // or 'time'
    minDate: new Date() - 10000,
    allowOldDates: true,
    allowFutureDates: false,
    doneButtonLabel: 'DONE',
    doneButtonColor: '#F2F3F4',
    cancelButtonLabel: 'CANCEL',
    cancelButtonColor: '#000000'
    };
  
    $scope.popupDate = function(){
    console.log("in the popup");
      $cordovaDatePicker.show(options).then(function(date){
         console.log("date is", date);
      });

This works fine at first. 

The first time I press it I get the datepicker. Fine. The second time nothing and this error in console:

    TypeError: undefined is not a function
    at DatePicker.show (http://192.168.1.35:8100/plugins/com.plugin.datepicker/www/android/DatePicker.js:19:32)
    at Object.show (http://192.168.1.35:8100/lib/ngCordova/dist/ng-cordova.js:1272:28)
    at Scope.$scope.popupDate (http://192.168.1.35:8100/js/settings.js:89:26)
    at $parseFunctionCall (http://192.168.1.35:8100/lib/ionic/js/ionic.bundle.js:20124:18)
    at http://192.168.1.35:8100/lib/ionic/js/ionic.bundle.js:50863:9
    at Scope.$eval (http://192.168.1.35:8100/lib/ionic/js/ionic.bundle.js:22178:28)
    at Scope.$apply (http://192.168.1.35:8100/lib/ionic/js/ionic.bundle.js:22276:23)
    at HTMLButtonElement.<anonymous> (http://192.168.1.35:8100/lib/ionic/js/ionic.bundle.js:50862:13)
    at HTMLButtonElement.eventHandler (http://192.168.1.35:8100/lib/ionic/js/ionic.bundle.js:10823:21)
    at triggerMouseEvent (http://192.168.1.35:8100/lib/ionic/js/ionic.bundle.js:2811:7)

**Comment by aelx311** [comment]
I get it to work by giving the options to .show() every time it is called.

**Comment by nikolayhg** [comment]
The problem is that after the first show the type of ```options.date``` is a string and not an object/date. You could call e.g. ```options.date = new Date()``` before the ```show(...)``` call to fix that.

**Comment by agupta1989** [comment]
Thanks @nikolaygit ! it helped me.

**Comment by phanthinh** [comment]
It's easy issue, Just call options will be instantiated on every click then it's work fine
